version: '3.0'
services:
  docker-emacs:
    container_name: 'docker-emacs27'
    hostname: 'docker-emacs27'
    build: ./
    working_dir: $HOME
    volumes:
      - ./entrypoint.sh:/tmp/entrypoint.sh
      - ./home:$HOME
      - $DOCKER_EMACS_PRJ:/$HOME/prj
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - $HOME/.ssh:/tmp/.ssh
      - $HOME/.gitconfig:/root/.gitconfig
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    environment:
      - DISPLAY=$DISPLAY
      - NO_AT_BRIDGE=1
    command: bash /tmp/entrypoint.sh
